### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by osmalpkoras** [lingchensanwen/QUDeval#1]
Hey everybody,

I was wondering if and when the code for this exciting project will be released. Is there an ETA?
I would like to evaluate my own QUD parser using your evaluation suite :) 

Thank you very much for all your efforts!

Kind regards,
Osman

**Comment by lingchensanwen** [comment]
Hi Osman, 

Thank you for your interest! We'll clean and release it asap. We'll see if that's possible to release it by the end of this week. I'll keep you posted once that's ready.

Best,
Yating

**Comment by lingchensanwen** [comment]
Hi Osman, I've uploaded part of our code to it. Another author is also working on this. You can check the progress over [this file](https://github.com/lingchensanwen/QUDeval/blob/main/code/readme.md). We will let you know once it's ready. And thank you again for your interest on our work. The data collection framework is also [released here](https://github.com/lingchensanwen/QUD-eval-data-collection-flask)

**Comment by lingchensanwen** [comment]
Hi Osman, We've released all the code. Please let us know if you have any questions on them.

**Comment by osmalpkoras** [comment]
Thank you very much! I will try it out anytime soon! :)
